### ISSUE TITLE
What is the expected behavior if handler is called twice?

### ISSUE THREAD

**Issue by alihammad-gist** [php-fig/http-server-middleware#5]
Is there an expected behavior if the continuation is called more than once? `$handler->handle(request)`

**Comment by shadowhand** [comment]
The handler should work the same no matter how many times it is called.

**Comment by alihammad-gist** [comment]
Sorry for making you repeat yourself. I mean't in the context of a Middleware queue. Given a middleware queue, as the standard does allude to middleware working together with "other" middlewares in producing a response, I suppose using the passed in $handler. What happens if I call the $handler more than once? In continuation passing style once the continuation is invoked any remaining computations in the current context are ignored. 
```scheme
(call/cc
  (lambda (k)
    (* 5 (k 4))))  => 4 
```

**Comment by shadowhand** [comment]
The handler should work the same no matter how many times it is called. It may fork in the code based on conditions in the request, but the handler can be executed multiple times with different requests.

There is no restriction on invoking the same handler multiple times.

**Comment by alihammad-gist** [comment]
Thank you.
