### ISSUE TITLE
Before type middlewares problem

### ISSUE THREAD

**Issue by ybelenko** [php-fig/http-server-middleware#7]
Correct me if I'm wrong, but main goal of this interface is provide universal way to create single middleware for all frameworks which supports `PSR-15 MiddlewareInterface`. And it works perfect with **AFTER** middlewares.

Let's say I need to create middleware that returns static response **BEFORE** next handlers. Basic example:
```php
class BeforeMiddleware implements MiddlewareInterface
{

    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        // I want send response right away, right here
        // I don't have any ResponseInterface instance to do that
        // the only way I can do that is
        $response = $handler->handle($request);
        $response->getBody()->write('After middleware from this point, not before');
        return $response;
    }
}
```

Need a real example where **BEFORE** middleware makes sense? When I implement OAuth2 authorization framework I need to validate credentials from request and return `401 Unauthorized` on fail. Of course I can do `$response = $handler->handle($request);` and then add HTTP Headers, but there will be some troubles:
* Any next handler can throw `exception`/`error` and exit immediately before my code.
* I need clean response instance or I have to reset it somehow. All HTTP Headers added by following handlers need to be erased, response body should be overwritten.
* Useless extra code execution and CPU loading. Imagine when next handlers send queries to database for data that we won't use, because user not authorized to see it.

---------

So my questions are:
* Is there any workarounds to create **BEFORE** middleware?
* Can I get `ResponseInterface` instance without `$handler->handle($request)` execution?

**Comment by shadowhand** [comment]
We can use PSR-17 response factory in the mediate to create a response and never call the handler.

**Comment by ybelenko** [comment]
@shadowhand thanks for the quick answer.

Yeah, I realized it recently. User can pass response factory as constructor argument of middleware. It's not convenient, but it's still a workaround. It would be great to have factory as third argument in `process` method, but I understand that this interface will not be changed in foreseeable future by obvious reasons.

Do you think that **before** middleware is so rare use case? Maybe you should describe somewhere in documentation how to create response without calling handler?

**Comment by shadowhand** [comment]
@ybelenko The specification is not going to change to add the factory to `MiddlewareInterface::process` without a new specification to replace PSR-15. Passing `ResponseFactoryInterface` and `StreamFactoryInterface` to the constructor of the middleware is the best solution right now, and follows DI principle.
